language: generic
dist: bionic
os: linux
env:
  global:
    - DEVKITPRO=$HOME
    - DEVKITARM=$DEVKITPRO/devkitARM
addons:
  apt:
    packages:
      - gcc-multilib
      - jq
      - linux-libc-dev
      - zlib-dev
cache:
  apt: true
install:
  - pushd $HOME
  - travis_retry wget https://github.com/devkitPro/buildscripts/releases/download/devkitARM_r52/devkitARM_r52-linux.tar.xz
  - tar xJf devkitARM*.tar.xz
  - travis_retry wget https://github.com/devkitPro/devkitarm-rules/releases/download/v1.0.0/devkitarm-rules-1.0.0.tar.xz
  - tar xJf devkitarm-rules-*.tar.xz -C $DEVKITARM
  - travis_retry git clone https://github.com/pret/agbcc.git
  - cd agbcc && sh build.sh && sh install.sh $TRAVIS_BUILD_DIR
  - popd
jobs:
  include:
    - os: linux
      addons:
        apt:
          sources:
              - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: _="Build"
      script:
        - make tools CXX=g++-7
        - make -j2 compare
        - make -j2 compare_leafgreen
        - make -j2 compare_firered_rev1
        - make -j2 compare_leafgreen_rev1
        - make -j2 modern
        - make -j2 leafgreen_modern
        - make -j2 firered_rev1_modern
        - make -j2 leafgreen_rev1_modern
after_success:
  - .travis/calcrom/webhook.sh pokefirered
