name: CI

on:
  push:
    branches:
      - master
      - no-ql-and-hs
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: FIRERED
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      COMPARE: 0
      UNUSED_ERROR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi libpng-dev python3
        # build-essential and git are already installed

      - name: Firered
        env:
          GAME_VERSION: FIRERED
        run: make -j${nproc} -O all

      - name: Leafgreen
        env:
          GAME_VERSION: LEAFGREEN
        run: make -j${nproc} -O all

      - name: Test
        env:
          TEST: 1
        run: |
          make -j${nproc} check
